### ISSUE TITLE
remove NO DATA when there ain't an editor

### ISSUE THREAD

**Issue by KumailRajani** [pooya-raz/tub-tex-maker#39]

**Comment by KumailRajani** [comment]
See this: al-Burhān fī wujūh al-bayān, NO DATA (n.plac., n.pub., 1930)

We don't want that NO DATA

**Comment by pooya-raz** [comment]
This was a tricky one. The NO DATA was because there was no edition type, not because there wasn't an editor.

**Comment by KumailRajani** [comment]
Well, in the process of finding solution you also found the problem....It should have been other way round...My apologies

**Comment by pooya-raz** [comment]
haha, there is nothing to apologise for. You were right in making a ticket, because the NO DATA shouldn't have been in the text.
